
kind: pipeline
name: main

steps:
- name: build
  image: golang
  commands:
    - export GOPATH="$HOME"
    - go get -d
    - go build
    - ls -l

- name: test
  image: golang
  environment:
    BITLY_TOKEN:
      from_secret: bitly_token
  commands:
    - ls -l
    - ./hobbit https://google.com